import = [
    "~/.config/alacritty/alacritty-theme/themes/carbonfox.toml"
]

[window]
padding.x = 6
padding.y = 3
decorations = "Buttonless"
opacity = 0.8
blur = true
dimensions.columns = 120
dimensions.lines = 40

[font]
size = 15
normal.family = "MesloLGS Nerd Font Mono"
