import = [
    "~/.config/alacritty/alacritty-theme/themes/carbonfox.toml"
]

[window]
padding.x = 6
padding.y = 3
decorations = "Buttonless"
opacity = 0.8
blur = true

[font]
size = 12
normal.family = "MesloLGS Nerd Font Mono"
